version: '3.8'

services:
    web:
        build:
            context: ./components/web
        command: gunicorn --bind 0.0.0.0:5000 run:app
        expose:
            - 5000
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=web_01
            
    nginx:
        build: ./components/nginx
        ports: 
            - 1337:80
        depends_on:
            - web